//
//  Nations.swift
//  TableSample
//
//  Created by Kiyong Kim on 2017. 8. 21..
//  Copyright © 2017년 KPU ios app dev. All rights reserved.
//

import Foundation

struct Country: Identifiable {
    let name: String
    let file: String
    var id: String { name }
}

struct Continent: Identifiable {
    let region: String
    let countries: [Country]
    var id: String { region }
}

struct Nations {
    static let continents: [Continent] = [
        Continent(region:"Africa, Middle East, and India",
         countries:[Country(name:"Armenia", file:"armenia"),
                    Country(name:"Botswana", file:"botswana"),
                    Country(name:"Bahrain", file:"bahrain"),
                    Country(name:"Cameroun", file:"cameroon"),
                    Country(name:"Centre Afrique", file:"central_african_republic"),
                    Country(name:"Côte d'Ivoire", file:"cotedivoire"),
                    Country(name:"Egypt", file:"egypt"),
                    Country(name:"Guinea-Bissau", file:"guinea_bisseau"),
                    Country(name:"Guinée", file:"guinea"),
                    Country(name:"Guinée Equatoriale", file:"equatorial_guinea"),
                    Country(name:"India", file:"india"),
                    Country(name:"Israel", file:"israel"),
                    Country(name:"Jordan", file:"jordan"),
                    Country(name:"Kenya", file:"kenya"),
                    Country(name:"Kuwait", file:"kuwait"),
                    Country(name:"Madagascar", file:"madagascar"),
                    Country(name:"Mali", file:"mali"),
                    Country(name:"Maroc", file:"morocco"),
                    Country(name:"Mauritius", file:"mauritius"),
                    Country(name:"Mozambique", file:"mozambique"),
                    Country(name:"Niger", file:"niger"),
                    Country(name:"Nigeria", file:"nigeria"),
                    Country(name:"Oman", file:"oman"),
                    Country(name:"Qatar", file:"qatar"),
                    Country(name:"Saudi Arabia", file:"saudi_arabia"),
                    Country(name:"Sénégal", file:"senegal"),
                    Country(name:"South Africa", file:"south_africa"),
                    Country(name:"Tunisie", file:"tunisia"),
                    Country(name:"Uganda", file:"uganda"),
                    Country(name:"United Arab Emirates", file:"united_arab_emirates"),
                    ]),
        Continent(region:"Asia Pacific",
         countries:[Country(name:"Australia", file:"australia"),
                    Country(name:"中国", file:"china"),
                    Country(name:"Hong Kong (English)", file:"hong_kong"),
                    Country(name:"香港", file:"hong_kong"),
                    Country(name:"Indonesia", file:"indonesia"),
                    Country(name:"日本", file:"japan"),
                    Country(name:"대한민국", file:"south_korea"),
                    Country(name:"Malaysia", file:"malaysia"),
                    Country(name:"New Zealand", file:"new_zealand"),
                    Country(name:"Philippines", file:"philippines"),
                    Country(name:"Singapore", file:"singapore"),
                    Country(name:"台灣", file:"taiwan"),
                    Country(name:"Thailand", file:"thailand"),
                    Country(name:"Vietnam", file:"vietnam"),
                    Country(name:"Other Asia", file:"generic"),
                    ]),
        Continent(region:"Europe",
         countries:[Country(name:"België", file:"belgium"),
                    Country(name:"Belgique", file:"belgium"),
                    Country(name:"България", file:"bulgaria"),
                    Country(name:"Česká republika", file:"czech_republic"),
                    Country(name:"Danmark", file:"denmark"),
                    Country(name:"Deutschland", file:"germany"),
                    Country(name:"Eesti", file:"estonia"),
                    Country(name:"España", file:"spain"),
                    Country(name:"France", file:"france"),
                    Country(name:"Greece", file:"greece"),
                    Country(name:"Hrvatska", file:"croatia"),
                    Country(name:"Ireland", file:"ireland"),
                    Country(name:"Italia", file:"italy"),
                    Country(name:"Latvija", file:"latvia"),
                    Country(name:"Liechtenstein", file:"liechtenstein"),
                    Country(name:"Lietuva", file:"lithuania"),
                    Country(name:"Luxembourg", file:"luxembourg"),
                    Country(name:"Macedonia", file:"macedonia"),
                    Country(name:"Magyarország", file:"hungary"),
                    Country(name:"Malta", file:"malta"),
                    Country(name:"Moldova", file:"moldova"),
                    Country(name:"Montenegro", file:"montenegro"),
                    Country(name:"Nederland", file:"netherlands"),
                    Country(name:"Norge", file:"norway"),
                    Country(name:"Österreich", file:"austria"),
                    Country(name:"Polska", file:"poland"),
                    Country(name:"Portugal", file:"portugal"),
                    Country(name:"România", file:"romania"),
                    Country(name:"Россия", file:"russia"),
                    Country(name:"Slovakia", file:"slovak_republic"),
                    Country(name:"Slovenia", file:"slovenia"),
                    Country(name:"Schweiz", file:"switzerland"),
                    Country(name:"Suisse", file:"switzerland"),
                    Country(name:"Suomi", file:"finland"),
                    Country(name:"Sverige", file:"sweden"),
                    Country(name:"Türkiye", file:"turkey"),
                    Country(name:"UK", file:"uk"),
                    ]),
        Continent(region:"Latin America and the Caribbean",
         countries:[Country(name:"Anguilla", file:"anguilla"),
                    Country(name:"Antigua & Barbuda", file:"antigua"),
                    Country(name:"Argentina", file:"argentina"),
                    Country(name:"Barbados", file:"barbados"),
                    Country(name:"Belize", file:"belize"),
                    Country(name:"Bermuda", file:"bermuda"),
                    Country(name:"Bolivia", file:"bolivia"),
                    Country(name:"Brasil", file:"brazil"),
                    Country(name:"British Virgin Islands", file:"british-virgin-islands"),
                    Country(name:"Cayman Islands", file:"cayman-islands"),
                    Country(name:"Chile", file:"chile"),
                    Country(name:"Colombia", file:"colombia"),
                    Country(name:"Costa Rica", file:"costa_rica"),
                    Country(name:"Dominica", file:"dominica"),
                    Country(name:"República Dominicana", file:"dominican_republic"),
                    Country(name:"Ecuador", file:"ecuador"),
                    Country(name:"El Salvador", file:"el_salvador"),
                    Country(name:"Grenada", file:"grenada"),
                    Country(name:"Guatemala", file:"guatemala"),
                    Country(name:"Guyana", file:"guyana"),
                    Country(name:"Honduras", file:"honduras"),
                    Country(name:"Jamaica", file:"jamaica"),
                    Country(name:"México", file:"mexico"),
                    Country(name:"Montserrat", file:"montserrat"),
                    Country(name:"Nicaragua", file:"nicaragua"),
                    Country(name:"Panamá", file:"panama"),
                    Country(name:"Paraguay", file:"paraguay"),
                    Country(name:"Perú", file:"peru"),
                    Country(name:"St. Kitts & Nevis", file:"st-kitts-nevis"),
                    Country(name:"St. Lucia", file:"st-lucia"),
                    Country(name:"St. Vincent & The Grenadines", file:"st-vincent"),
                    Country(name:"Suriname", file:"suriname"),
                    Country(name:"The Bahamas", file:"bahamas"),
                    Country(name:"Trinidad & Tobago", file:"trinidad"),
                    Country(name:"Turks & Caicos", file:"turks_caicos"),
                    Country(name:"Uruguay", file:"uruguay"),
                    Country(name:"Venezuela", file:"venezuela"),
                    Country(name:"América Latina y el Caribe (español)", file:"generic"),
                    Country(name:"Latin America and the Caribbean (English)", file:"generic"),
                    ]),
        Continent(region:"The United States, Canada, and Puerto Rico",
         countries:[Country(name:"Canada (English)", file:"canada"),
                    Country(name:"Canada (Français)", file:"canada"),
                    Country(name:"Puerto Rico (English)", file:"puerto_rico"),
                    Country(name:"Puerto Rico (español)", file:"puerto_rico"),
                    Country(name:"USA", file:"usa"),
                    ]),
        ]
}
