//
//  Nations.swift
//  TableSample
//
//  Created by Kiyong Kim on 2017. 8. 21..
//  Copyright © 2017년 KPU ios app dev. All rights reserved.
//

import Foundation

struct Country: Identifiable {
    let name: String
    let file: String
    var id: String { name }
}

struct Continent: Identifiable {
    let region: String
    let countries: [Country]
    var id: String { region }
}

struct Nations {
    static let contintents: [Continent] = [
        Continent(region:"Africa, Middle East, and India",
         countries:[Country(name:"Armenia", file:"armenia.png"),
                    Country(name:"Botswana", file:"botswana.png"),
                    Country(name:"Bahrain", file:"bahrain.png"),
                    Country(name:"Cameroun", file:"cameroon.png"),
                    Country(name:"Centre Afrique", file:"central_african_republic.png"),
                    Country(name:"Côte d'Ivoire", file:"cotedivoire.png"),
                    Country(name:"Egypt", file:"egypt.png"),
                    Country(name:"Guinea-Bissau", file:"guinea_bisseau.png"),
                    Country(name:"Guinée", file:"guinea.png"),
                    Country(name:"Guinée Equatoriale", file:"equatorial_guinea.png"),
                    Country(name:"India", file:"india.png"),
                    Country(name:"Israel", file:"israel.png"),
                    Country(name:"Jordan", file:"jordan.png"),
                    Country(name:"Kenya", file:"kenya.png"),
                    Country(name:"Kuwait", file:"kuwait.png"),
                    Country(name:"Madagascar", file:"madagascar.png"),
                    Country(name:"Mali", file:"mali.png"),
                    Country(name:"Maroc", file:"morocco.png"),
                    Country(name:"Mauritius", file:"mauritius.png"),
                    Country(name:"Mozambique", file:"mozambique.png"),
                    Country(name:"Niger", file:"niger.png"),
                    Country(name:"Nigeria", file:"nigeria.png"),
                    Country(name:"Oman", file:"oman.png"),
                    Country(name:"Qatar", file:"qatar.png"),
                    Country(name:"Saudi Arabia", file:"saudi_arabia.png"),
                    Country(name:"Sénégal", file:"senegal.png"),
                    Country(name:"South Africa", file:"south_africa.png"),
                    Country(name:"Tunisie", file:"tunisia.png"),
                    Country(name:"Uganda", file:"uganda.png"),
                    Country(name:"United Arab Emirates", file:"united_arab_emirates.png"),
                    ]),
        Continent(region:"Asia Pacific",
         countries:[Country(name:"Australia", file:"australia.png"),
                    Country(name:"中国", file:"china.png"),
                    Country(name:"Hong Kong (English)", file:"hong_kong.png"),
                    Country(name:"香港", file:"hong_kong.png"),
                    Country(name:"Indonesia", file:"indonesia.png"),
                    Country(name:"日本", file:"japan.png"),
                    Country(name:"대한민국", file:"south_korea.png"),
                    Country(name:"Malaysia", file:"malaysia.png"),
                    Country(name:"New Zealand", file:"new_zealand.png"),
                    Country(name:"Philippines", file:"philippines.png"),
                    Country(name:"Singapore", file:"singapore.png"),
                    Country(name:"台灣", file:"taiwan.png"),
                    Country(name:"Thailand", file:"thailand.png"),
                    Country(name:"Vietnam", file:"vietnam.png"),
                    Country(name:"Other Asia", file:"generic.png"),
                    ]),
        Continent(region:"Europe",
         countries:[Country(name:"België", file:"belgium.png"),
                    Country(name:"Belgique", file:"belgium.png"),
                    Country(name:"България", file:"bulgaria.png"),
                    Country(name:"Česká republika", file:"czech_republic.png"),
                    Country(name:"Danmark", file:"denmark.png"),
                    Country(name:"Deutschland", file:"germany.png"),
                    Country(name:"Eesti", file:"estonia.png"),
                    Country(name:"España", file:"spain.png"),
                    Country(name:"France", file:"france.png"),
                    Country(name:"Greece", file:"greece.png"),
                    Country(name:"Hrvatska", file:"croatia.png"),
                    Country(name:"Ireland", file:"ireland.png"),
                    Country(name:"Italia", file:"italy.png"),
                    Country(name:"Latvija", file:"latvia.png"),
                    Country(name:"Liechtenstein", file:"liechtenstein.png"),
                    Country(name:"Lietuva", file:"lithuania.png"),
                    Country(name:"Luxembourg", file:"luxembourg.png"),
                    Country(name:"Macedonia", file:"macedonia.png"),
                    Country(name:"Magyarország", file:"hungary.png"),
                    Country(name:"Malta", file:"malta.png"),
                    Country(name:"Moldova", file:"moldova.png"),
                    Country(name:"Montenegro", file:"montenegro.png"),
                    Country(name:"Nederland", file:"netherlands.png"),
                    Country(name:"Norge", file:"norway.png"),
                    Country(name:"Österreich", file:"austria.png"),
                    Country(name:"Polska", file:"poland.png"),
                    Country(name:"Portugal", file:"portugal.png"),
                    Country(name:"România", file:"romania.png"),
                    Country(name:"Россия", file:"russia.png"),
                    Country(name:"Slovakia", file:"slovak_republic.png"),
                    Country(name:"Slovenia", file:"slovenia.png"),
                    Country(name:"Schweiz", file:"switzerland.png"),
                    Country(name:"Suisse", file:"switzerland.png"),
                    Country(name:"Suomi", file:"finland.png"),
                    Country(name:"Sverige", file:"sweden.png"),
                    Country(name:"Türkiye", file:"turkey.png"),
                    Country(name:"UK", file:"uk.png"),
                    ]),
        Continent(region:"Latin America and the Caribbean",
         countries:[Country(name:"Anguilla", file:"anguilla.png"),
                    Country(name:"Antigua & Barbuda", file:"antigua.png"),
                    Country(name:"Argentina", file:"argentina.png"),
                    Country(name:"Barbados", file:"barbados.png"),
                    Country(name:"Belize", file:"belize.png"),
                    Country(name:"Bermuda", file:"bermuda.png"),
                    Country(name:"Bolivia", file:"bolivia.png"),
                    Country(name:"Brasil", file:"brazil.png"),
                    Country(name:"British Virgin Islands", file:"british-virgin-islands.png"),
                    Country(name:"Cayman Islands", file:"cayman-islands.png"),
                    Country(name:"Chile", file:"chile.png"),
                    Country(name:"Colombia", file:"colombia.png"),
                    Country(name:"Costa Rica", file:"costa_rica.png"),
                    Country(name:"Dominica", file:"dominica.png"),
                    Country(name:"República Dominicana", file:"dominican_republic.png"),
                    Country(name:"Ecuador", file:"ecuador.png"),
                    Country(name:"El Salvador", file:"el_salvador.png"),
                    Country(name:"Grenada", file:"grenada.png"),
                    Country(name:"Guatemala", file:"guatemala.png"),
                    Country(name:"Guyana", file:"guyana.png"),
                    Country(name:"Honduras", file:"honduras.png"),
                    Country(name:"Jamaica", file:"jamaica.png"),
                    Country(name:"México", file:"mexico.png"),
                    Country(name:"Montserrat", file:"montserrat.png"),
                    Country(name:"Nicaragua", file:"nicaragua.png"),
                    Country(name:"Panamá", file:"panama.png"),
                    Country(name:"Paraguay", file:"paraguay.png"),
                    Country(name:"Perú", file:"peru.png"),
                    Country(name:"St. Kitts & Nevis", file:"st-kitts-nevis.png"),
                    Country(name:"St. Lucia", file:"st-lucia.png"),
                    Country(name:"St. Vincent & The Grenadines", file:"st-vincent.png"),
                    Country(name:"Suriname", file:"suriname.png"),
                    Country(name:"The Bahamas", file:"bahamas.png"),
                    Country(name:"Trinidad & Tobago", file:"trinidad.png"),
                    Country(name:"Turks & Caicos", file:"turks_caicos.png"),
                    Country(name:"Uruguay", file:"uruguay.png"),
                    Country(name:"Venezuela", file:"venezuela.png"),
                    Country(name:"América Latina y el Caribe (español)", file:"generic.png"),
                    Country(name:"Latin America and the Caribbean (English)", file:"generic.png"),
                    ]),
        Continent(region:"The United States, Canada, and Puerto Rico",
         countries:[Country(name:"Canada (English)", file:"canada.png"),
                    Country(name:"Canada (Français)", file:"canada.png"),
                    Country(name:"Puerto Rico (English)", file:"puerto_rico.png"),
                    Country(name:"Puerto Rico (español)", file:"puerto_rico.png"),
                    Country(name:"USA", file:"usa.png"),
                    ]),
        ]
}
